"use client";
import { FormEvent, useMemo, useState } from "react";
import { Gift, Languages, Send, Sparkles } from "lucide-react";
import { ChatMessage } from "./ChatMessage";
import { TypingIndicator } from "./TypingIndicator";
import { DeliveryEstimator } from "./DeliveryEstimator";
import { useCartStore } from "@/lib/store/useCartStore";
import { Message, Product } from "@/lib/types";
const starters = ["Gift for girlfriend under Rs 5000", "Surprise me for Amma birthday", "Urgent groceries in Colombo", "Avurudu hamper for relatives"];
export function ChatWindow() {
  const language = useCartStore((s) => s.language); const setLanguage = useCartStore((s) => s.setLanguage);
  const [input, setInput] = useState(""); const [loading, setLoading] = useState(false);
  const welcome = language === "si" ? "Ayubowan. Mama KAPRUKA AI AGENT. Gift, grocery, cake, flowers, electronics, baby care, anything Sri Lanka context ekka hoyala dennam." : "Ayubowan. I am KAPRUKA AI AGENT. Tell me who it is for, the occasion, budget, and delivery city; I will think like a Sri Lankan shopping expert.";
  const [messages, setMessages] = useState<Message[]>([{ id: "welcome", role: "assistant", content: welcome }]);
  const canSend = useMemo(() => input.trim().length > 1 && !loading, [input, loading]);
  async function sendMessage(text = input) { const clean = text.trim(); if (!clean || loading) return; const userMessage: Message = { id: crypto.randomUUID(), role: "user", content: clean }; const assistantId = crypto.randomUUID(); setMessages((prev) => [...prev, userMessage, { id: assistantId, role: "assistant", content: "" }]); setInput(""); setLoading(true); try { const res = await fetch("/api/chat", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ message: clean, language }) }); const reader = res.body?.getReader(); const decoder = new TextDecoder(); if (!reader) throw new Error("No stream"); let buffer = ""; while (true) { const { done, value } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const chunks = buffer.split("\n\n"); buffer = chunks.pop() ?? ""; for (const chunk of chunks) { const line = chunk.replace(/^data: /, ""); if (!line) continue; const data = JSON.parse(line) as { token?: string; done?: boolean; products?: Product[] }; if (data.token) setMessages((prev) => prev.map((msg) => msg.id === assistantId ? { ...msg, content: msg.content + data.token } : msg)); if (data.done) setMessages((prev) => prev.map((msg) => msg.id === assistantId ? { ...msg, products: data.products ?? [] } : msg)); } } } finally { setLoading(false); } }
  function onSubmit(e: FormEvent) { e.preventDefault(); void sendMessage(); }
  return <section className="relative mx-auto flex h-[100dvh] w-full max-w-7xl gap-4 p-3 md:p-5"><aside className="hidden w-72 shrink-0 flex-col gap-3 rounded-[8px] bg-kapruka-purple p-4 text-white shadow-glow lg:flex"><div><p className="text-xs font-black uppercase text-kapruka-yellow">KAPRUKA AI AGENT</p><h1 className="mt-2 text-3xl font-black leading-tight">Sri Lanka's smartest shopping assistant</h1></div><DeliveryEstimator/><div className="rounded-[8px] bg-white/10 p-3 text-sm text-white/80">Smart Gift Mode, Surprise Me bundles, budget-aware filtering, delivery intelligence, and session memory are built into this flow.</div></aside><main className="flex min-w-0 flex-1 flex-col overflow-hidden rounded-[8px] bg-kapruka-purple shadow-glow"><header className="flex items-center justify-between border-b border-white/10 px-4 py-3 text-white"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-[8px] bg-kapruka-yellow text-kapruka-purple"><Sparkles size={20}/></div><div><h2 className="font-black">KAPRUKA AI AGENT</h2><p className="text-xs text-white/65">Cakes, gifts, groceries, electronics, flowers, baby care and more</p></div></div><button onClick={() => setLanguage(language === "en" ? "si" : "en")} className="flex items-center gap-2 rounded-[8px] bg-white/10 px-3 py-2 text-sm font-bold hover:bg-white/15"><Languages size={16}/>{language === "en" ? "Sinhala" : "English"}</button></header><div className="flex-1 space-y-4 overflow-y-auto p-4 scrollbar-thin">{messages.map((message) => <ChatMessage key={message.id} message={message}/>)}{loading ? <TypingIndicator/> : null}</div><div className="border-t border-white/10 p-3"><div className="mb-2 flex gap-2 overflow-x-auto pb-1">{starters.map((starter) => <button key={starter} onClick={() => void sendMessage(starter)} className="shrink-0 rounded-[8px] bg-white/10 px-3 py-2 text-xs font-semibold text-white hover:bg-white/15"><Gift size={13} className="mr-1 inline"/>{starter}</button>)}</div><form onSubmit={onSubmit} className="flex gap-2"><input value={input} onChange={(e) => setInput(e.target.value)} placeholder={language === "si" ? "Mokakda hoyanne?" : "Ask for a gift, daily need, budget, or delivery city"} className="min-w-0 flex-1 rounded-[8px] border border-white/10 bg-white px-4 py-3 text-kapruka-ink outline-none"/><button disabled={!canSend} className="grid h-12 w-12 place-items-center rounded-[8px] bg-kapruka-yellow text-kapruka-purple disabled:opacity-50"><Send size={18}/></button></form></div></main></section>;
}
